#include <SFML/Graphics.hpp>
#include <vector>
#include <memory>
#include <string>
#include "Worm.h"
#include "Enum.h"
#include "Attack.h"
#include "Resources.h"
#include "Timer.h"
#include "Grenade.h"
#include "Sheep.h"
#include "Flik.h"
#include "Axe.h"
#include "Stinky.h"
#include "Transform.h"
#include "WhiteFlag.h"
#include "Pass.h"
#include "Board.h"

#include "staticObject.h"
